masks:
  kind: none

# The probability of applying the augmentation.
# Identity and cropping are sampled first, then other augs, if multiple augs are sampled.
augs:
  identity:           2
  crop:               1
  hflip:              1
  rotate:             1
  perspective:        1
  jpeg:               1
  gaussian_blur:      1
  median_filter:      0
  brightness:         1
  contrast:           1
  saturation:         1
  hue:                0

# The parameters for each augmentation.
# edge size will be sampled in area size
augs_params:
  crop:
    min_size: 0.05
    max_size: 1.00
  rotate:
    min_angle: -45
    max_angle: 45
    do90: true
  perspective:
    min_distortion_scale: 0.01
    max_distortion_scale: 0.40
  jpeg:
    min_quality: 30
    max_quality: 80
  gaussian_blur:
    # sigma = 0.3 * ((kernel_size - 1) * 0.5 - 1) + 0.8
    min_kernel_size: 3
    max_kernel_size: 17
  median_filter:
    min_kernel_size: 3
    max_kernel_size: 7
  brightness:
    min_factor: 0.3
    max_factor: 2.2
  contrast:
    min_factor: 0.3
    max_factor: 2.2
  saturation:
    min_factor: 0.3
    max_factor: 2.2
  hue:
    min_factor: -0.3
    max_factor: 0.3
