model: unet_small2_yuv_quant

unet_small2_yuv_quantizable:
  in_channels: 1
  out_channels: 1
  z_channels: 16
  num_blocks: 8
  activation: 'relu'
  normalization: 'batch'
  z_channels_mults: [1, 2, 4, 8]
  last_tanh: True

unet_small2_yuv:
  in_channels: 1
  out_channels: 1
  z_channels: 16
  num_blocks: 8
  activation: 'gelu'
  normalization: 'group'
  z_channels_mults: [1, 2, 4, 8]
  last_tanh: True