model:
  base_learning_rate: 4.5e-06
  target: deps.taming.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 8192
    ddconfig:
      double_z: false
      z_channels: 256
      resolution: 512
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    lossconfig:
      target: deps.taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_start: 0
        disc_weight: 0.75
        disc_num_layers: 2
        codebook_weight: 1.0
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 10
    image_size: 512
    filter_image_size: 512
    dataset: coco
    aesthetics_th: 0